In [1]:
import numpy as np
import pandas as pd
import holoviews as hv
from math import pi
import pandas as pd
from bokeh.io import output_file, show
from bokeh.palettes import Category20c
from bokeh.plotting import figure,ColumnDataSource
from bokeh.transform import cumsum
from bokeh.core.properties import value

In [3]:
data = pd.read_csv('C:/Users/Ceiec04/Desktop/Prediccion_Alertas_Alimentarias/Datasets/full_RASFF_DATA_16092019.csv', sep=';', 
                   header=0, index_col = 0)
data
alerts = data

In [5]:
a = alerts.loc[alerts['CLASSIF'] == 'border rejection']
b = pd.DataFrame(a[['CLASSIF','NOT_COUNTRY']])
c = b.groupby('NOT_COUNTRY').size()
d = pd.DataFrame(c).reset_index()
e = c.sort_values(ascending=False)
f = pd.DataFrame(e).reset_index()
g = f.loc[f['NOT_COUNTRY'].isin(['Spain','United Kingdom','Germany','Netherlands','France','Italy'])]
h = pd.DataFrame(g)
i = h.sort_values('NOT_COUNTRY')
border_list = i[0].values
print(border_list)

a = alerts.loc[alerts['CLASSIF'] == 'alert']
b = pd.DataFrame(a[['CLASSIF','NOT_COUNTRY']])
c = b.groupby('NOT_COUNTRY').size()
d = pd.DataFrame(c).reset_index()
e = c.sort_values(ascending=False)
f = pd.DataFrame(e).reset_index()
g = f.loc[f['NOT_COUNTRY'].isin(['Spain','United Kingdom','Germany','Netherlands','France','Italy'])]
h = pd.DataFrame(g)
i = h.sort_values('NOT_COUNTRY')
alert_list = i[0].values
print(alert_list)

a = alerts.loc[alerts['CLASSIF'] == 'information for attention']
b = pd.DataFrame(a[['CLASSIF','NOT_COUNTRY']])
c = b.groupby('NOT_COUNTRY').size()
d = pd.DataFrame(c).reset_index()
e = c.sort_values(ascending=False)
f = pd.DataFrame(e).reset_index()
g = f.loc[f['NOT_COUNTRY'].isin(['Spain','United Kingdom','Germany','Netherlands','France','Italy'])]
h = pd.DataFrame(g)
i = h.sort_values('NOT_COUNTRY')
follow_list = i[0].values
print(follow_list)

countries = ['Spain','United Kingdom','Germany','Netherlands','France','Italy']
clas = ['border rejection', 'alert', 'information for attention']
colors = ["#c9d9d3", "#718dbf", "#e84d60"]

data = {'countries' : countries,
        'border rejection'  : border_list,
        'alert'   : alert_list,
        'information for attention'   : follow_list}

p = figure(x_range = countries, plot_height=300, title="Alert classification by countries",
           toolbar_location=None, tools="hover", tooltips="$name @countries: @$name")

p.vbar_stack(clas, x='countries', width=0.9, color=colors, source=data, legend=[value(x) for x in clas])

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"
show(p)

[ 949 1617 2441 1846 2047 2781]
[1285 2393 2011 1008  264  902]
[394 539 970 379 210 597]
